<a href="https://colab.research.google.com/github/dewUmesh/pytorch/blob/main/LR_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
import numpy as np

In [7]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')



In [8]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [9]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [10]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [11]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [12]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1298, -0.2888,  0.0769],
        [-0.0395,  0.3708, -0.3984]], requires_grad=True)
Parameter containing:
tensor([0.4846, 0.3079], requires_grad=True)


In [13]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1298, -0.2888,  0.0769],
         [-0.0395,  0.3708, -0.3984]], requires_grad=True),
 Parameter containing:
 tensor([0.4846, 0.3079], requires_grad=True)]

In [14]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -6.0785,   5.1373],
        [ -8.1909,   3.8472],
        [-22.4551,  23.4516],
        [  4.1562,  -2.5170],
        [-12.8963,   5.2923],
        [ -5.6598,   4.7270],
        [ -7.8253,   3.0780],
        [-22.2483,  23.0137],
        [  3.7376,  -2.1067],
        [-12.9493,   4.9335],
        [ -5.7128,   4.3682],
        [ -7.7723,   3.4369],
        [-22.8207,  24.2207],
        [  4.2092,  -2.1581],
        [-13.3150,   5.7026]], grad_fn=<AddmmBackward0>)

In [15]:
# Import nn.functional
import torch.nn.functional as F

In [16]:
# Define loss function
loss_fn = F.mse_loss

In [17]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8559.2305, grad_fn=<MseLossBackward0>)


In [18]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [19]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [20]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 438.6514
Epoch [20/100], Loss: 282.3293
Epoch [30/100], Loss: 416.5470
Epoch [40/100], Loss: 86.8715
Epoch [50/100], Loss: 154.5603
Epoch [60/100], Loss: 67.4694
Epoch [70/100], Loss: 81.5435
Epoch [80/100], Loss: 78.7265
Epoch [90/100], Loss: 35.4676
Epoch [100/100], Loss: 54.9396
