<a href="https://colab.research.google.com/github/dewUmesh/pytorch/blob/main/LR_using_torch_inbuit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 we can train the model using the following steps:

  1. Generate predictions

  2. Calculate the loss

  3. Compute gradients w.r.t the weights and biases

  4. Adjust the weights by subtracting a small quantity proportional to the gradient

  5. Reset the gradients to zero


In [3]:
import torch
import numpy as np

# **Linear regression using pytorch inbuilt fetures**

In [4]:
import torch.nn as nn

In [5]:
# input features (temp,rainfall,humidity)
input = np.array([
                   [73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]
],dtype = 'float32')

In [6]:
# input targets
targets = np.array ([
                   [56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]

],dtype = 'float32')

Convert numpy to tensor

In [7]:
input = torch.from_numpy(input)

In [8]:
targets = torch.from_numpy(targets)

Use datasets and dataloader, for executing batches

In [9]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [11]:
dataset = TensorDataset(input, targets)
print (dataset[0:5])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]]))


In [42]:
databatches = DataLoader(dataset,5,shuffle=True)

In [43]:
for x,y in databatches:
  print (f"x= {x}")
  print (f"y= {y}")

x= tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [ 68.,  96.,  71.]])
y= tensor([[ 56.,  70.],
        [ 22.,  37.],
        [ 80., 102.],
        [118., 132.],
        [104., 118.]])
x= tensor([[ 74.,  66.,  43.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 73.,  66.,  44.],
        [ 87., 134.,  58.]])
y= tensor([[ 57.,  69.],
        [ 81., 101.],
        [103., 119.],
        [ 57.,  69.],
        [119., 133.]])
x= tensor([[103.,  43.,  36.],
        [101.,  44.,  37.],
        [ 87., 135.,  57.],
        [ 68.,  97.,  70.],
        [ 92.,  87.,  64.]])
y= tensor([[ 20.,  38.],
        [ 21.,  38.],
        [118., 134.],
        [102., 120.],
        [ 82., 100.]])


1. Declare model

2. Predict

3. Get Loss

4. Optimize

In [19]:
import torch.nn as nn

In [20]:
model = nn.Linear(3,2)

In [33]:
predict = model(input)

In [34]:
print (predict)

tensor([[-41.8512, -23.4280],
        [-48.4151, -28.7178],
        [-71.3304, -47.0411],
        [-47.8442, -18.1777],
        [-38.2956, -28.5307],
        [-41.8612, -23.1391],
        [-47.3869, -28.1332],
        [-71.2447, -46.9265],
        [-47.8342, -18.4666],
        [-37.2574, -28.2351],
        [-40.8230, -22.8434],
        [-48.4251, -28.4289],
        [-72.3586, -47.6257],
        [-48.8824, -18.4734],
        [-38.2856, -28.8196]], grad_fn=<AddmmBackward0>)


In [28]:
print (list(model.parameters()))


[Parameter containing:
tensor([[-0.4763, -0.4663,  0.5619],
        [-0.0905, -0.3794,  0.2051]], requires_grad=True), Parameter containing:
tensor([-0.0065, -0.2176], requires_grad=True)]


In [31]:
loss = nn.functional.mse_loss(predict,targets)

In [23]:
print (loss)

tensor(16972.8320, grad_fn=<MseLossBackward0>)


In [32]:
optimize = torch.optim.SGD(model.parameters(), lr = 1e-2)

In [25]:
print (optimize)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


# **Recursive model training**

In [53]:
def fit(num_epochs, model, loss_fn, opt, batches):
  # repeat for each batch
  for epoch in range(num_epochs):

    for x,y in batches:
      # 1. Predict
      prediction = model(x)
      # 2. Calculate loss
      loss = loss_fn(prediction,y)
      # 3. Compute change
      loss.backward()
      # 4. optimize
      opt.step()
      # 5. Reset grads
      opt.zero_grad()
    # print progess
    if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

# **Call fit**