<a href="https://colab.research.google.com/github/dewUmesh/pytorch/blob/main/pytorchBeginerBasicTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Basics: Tensors & Gradients
Part 1 of "Pytorch: Zero to GANs"

This post is the first in a series of tutorials on building deep learning models with PyTorch, an open source neural networks library developed and maintained by Facebook. Check out the full series:

    PyTorch Basics: Tensors & Gradients
    Linear Regression & Gradient Descent
    Image Classfication using Logistic Regression
    Training Deep Neural Networks on a GPU
    Image Classification using Convolutional Neural Networks
    Data Augmentation, Regularization and ResNets
    Generating Images using Generative Adverserial Networks

This series attempts to make PyTorch a bit more approachable for people starting out with deep learning and neural networks. In this notebook, we’ll cover the basic building blocks of PyTorch models: tensors and gradients.

In [2]:
import torch

PyTorch is a library for processing tensors.
Tensors is number, vector, matrix or an n-dimentional array.

Create a tensor with single number

In [5]:
t=torch.tensor(2.)
t

tensor(2.)

Here 2. is a shorthand used for floating numbers.

Let's find out the type of tensor

In [6]:
t.dtype

torch.float32

# 1. **Creare a vector tensor**

In [7]:
t= torch.tensor([1,2,3,4.])
t

tensor([1., 2., 3., 4.])

# **2. Create a matrix tensor**

In [13]:
t= torch.tensor([[1,2],[3,4]])
print (t)
print (t.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


# **3. Create three dimentional array**

In [17]:
t=torch.tensor([
    [
      [1,2,3],
      [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print (t)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
