<a href="https://colab.research.google.com/github/dewUmesh/pytorch/blob/main/pytorchBeginerBasicTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Basics: Tensors & Gradients
Part 1 of "Pytorch: Zero to GANs"

This post is the first in a series of tutorials on building deep learning models with PyTorch, an open source neural networks library developed and maintained by Facebook. Check out the full series:

    PyTorch Basics: Tensors & Gradients
    Linear Regression & Gradient Descent
    Image Classfication using Logistic Regression
    Training Deep Neural Networks on a GPU
    Image Classification using Convolutional Neural Networks
    Data Augmentation, Regularization and ResNets
    Generating Images using Generative Adverserial Networks

This series attempts to make PyTorch a bit more approachable for people starting out with deep learning and neural networks. In this notebook, we’ll cover the basic building blocks of PyTorch models: tensors and gradients.

In [2]:
import torch

PyTorch is a library for processing tensors.
Tensors is number, vector, matrix or an n-dimentional array.

Create a tensor with single number

In [5]:
t=torch.tensor(2.)
t

tensor(2.)

Here 2. is a shorthand used for floating numbers.

Let's find out the type of tensor

In [6]:
t.dtype

torch.float32

# 1. **Creare a vector tensor**

In [7]:
t= torch.tensor([1,2,3,4.])
t

tensor([1., 2., 3., 4.])

# **2. Create a matrix tensor**

In [13]:
t= torch.tensor([[1,2],[3,4]])
print (t)
print (t.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


# **3. Create three dimentional array**

In [17]:
t=torch.tensor([
    [
      [1,2,3],
      [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print (t)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


# **4. print shape of tensor**

In [21]:
print (t.shape)


torch.Size([2, 2, 3])


# **5. Tensor operations and gradients**

In [37]:
# Create a tensor
t1 = torch.tensor(2.)
w1 = torch.tensor(1.,requires_grad=True)
t2 = torch.tensor([1.,2])

# **5.1. Apply arithmetic operations**

In [27]:
x = t1 * t2
print (x)

y = x * w + t2
print (y)

tensor([2, 4])
tensor([3., 6.], grad_fn=<AddBackward0>)


In [28]:
z = t1 + t2
z

tensor([3, 4])

# **5.2. Compute  derivative of w**

In [38]:
x = torch.tensor (t1*t1, requires_grad=True)

<ipython-input-38-8550ad53f505>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor (t1*t1, requires_grad=True)


In [39]:
y = w * x + 1
y

tensor(5., grad_fn=<AddBackward0>)

In [40]:
y.backward()

# **6. Interoperability with numpy**

In [41]:
# Create a numpy array
import numpy as np

In [43]:
x = np.array([
             [1,2],
             [3,4]
             ])
print (x)

[[1 2]
 [3 4]]


In [44]:
# Convert to tesnsor
y = torch.from_numpy(x)
print (y)

tensor([[1, 2],
        [3, 4]])


In [46]:
# Convert tensor to numpy array
z = y.numpy()
print (z)

[[1 2]
 [3 4]]


# **Linear regression**

**Business problem:**

  *Predict crop **yields** for apple and oranges  temp,rainfall,humidity **input features** in a region.*

**Linear equation:**

  yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1

  yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
  

In [47]:
import numpy as np
import torch

In [50]:
# sample input data
# temp, rainfall,humidity
input = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ], dtype='float32'
)

targets = np.array(
    [
        [10,20],
        [30,40],
        [50,60]
    ], dtype='float32'

)

Tech Requirement

1.   Input matrix   
2.   Model
3.   Loss fucntion
4.   Optimizer



In [67]:
# Comvert input and target to tensor
input_tensor = torch.from_numpy(input)
target_tensor = torch.from_numpy(targets)

**Define weights and bias tensor**

In [68]:
w = torch.rand(3,2,requires_grad=True)
b = torch.rand(2, requires_grad=True)

print (w)
print (b)

tensor([[0.3419, 0.3965],
        [0.7626, 0.0654],
        [0.5707, 0.5896]], requires_grad=True)
tensor([0.3082, 0.8876], requires_grad=True)


# **Matrix multiplication : @**

**define a model function**

Matrix return would be a **prediction**

In [69]:
def model(input_matrix ):
  return input_matrix @ w + b

In [70]:
prediction = model (input_tensor)

print (prediction)

tensor([[ 3.8872,  3.1837],
        [ 8.9126,  6.3382],
        [13.9379,  9.4926]], grad_fn=<AddBackward0>)


# **Loss funtion : MSE**

In [71]:
def mse(prediction,target):
  diff = prediction - target
  return torch.sum(diff * diff) / diff.numel()

In [72]:
# calculate loss
loss = mse(prediction,target_tensor)
print (loss)

tensor(958.2366, grad_fn=<DivBackward0>)


# **Compute change : gradient **

In [73]:
loss.backward()

In [74]:
w.grad

tensor([[-114.2991, -168.3384],
        [-135.3865, -202.0002],
        [-156.4740, -235.6620]])

In [75]:
with torch.no_grad():
  w = w - w.grad * 1e-5
  b = b - b.grad * 1e-5

In [76]:
loss = mse(prediction,target_tensor)
print (loss)

tensor(958.2366, grad_fn=<DivBackward0>)


# **Important **

**Make grad to 0 **

In [83]:
w.zero_()
b.grad.zero_()



AttributeError: ignored

In [81]:
print (w.grad)
print (b.grad)

None
None
